name: Weekly Crypto Price Logger

on:
  workflow_dispatch:  # Manual trigger

jobs:
  fetch-price:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Log Bitcoin price
        run: python get_price.py